### PR TITLE
feat: NowFunc

### PR DESCRIPTION
**Pull request by thekuwayama**
This PR suggests ~using flextime~ adding NowFunc to make it easier to test.

### CODE REVIEW

**Review by mash — CHANGES_REQUESTED** [review]
Please create a NowFunc and do not add a dependency.

ref 
https://github.com/jinzhu/gorm/blob/master/utils.go#L20

**Comment by thekuwayama** [comment]
Thank you for comments!

I replaced flextime with NowFunc so as not to add a dependency.

**Review by mash — COMMENTED** [review]
Please check https://github.com/thekuwayama/go-limiter/pull/1

**Review by mash — APPROVED** [review]
LGTM!

**Pull request merged**
